---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php8.1
  name: phpcs
- commands:
  - vendor/bin/phan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1-ast
  name: phan
- commands:
  - vendor/bin/phpstan analyse src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1 lowest
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.2
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.3
services:
- image: memcached:alpine
  name: memcached
- image: redis:alpine
  name: redis
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.3
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.3
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: 62e1181809730e48a4f4a3e6b4cb9e566b585910805749be5b1877a98dc865a1

...
